# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the doc/source directory with Sphinx
sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: false

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3
  install:
    - requirements: doc/requirements.txt
